### ISSUE TITLE
Download PVOutput.org data for Italy and Malta

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#614]
## TODO:
- [ ] Pay for `getbatchstatus` access to Italy and Malta.
- [ ] Download data from PVOutput.org.
- [ ] Convert to intermediate format that `nowcasting_dataset` can use.

**Comment by peterdudfield** [comment]
https://github.com/openclimatefix/nowcasting_dataset/issues/573 - ill close this one
