### ISSUE TITLE
Get data from 2020-01-01 to 2021-10-01

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#81]
We're currently using less than 2 years of data.  But about 10 years of data is available!  More training data is usually a Good Thing :)

The priority is probably to forward-fill our training dataset (because the PV Live data & ESO's PV forecasts are both quite recent).

## Tasks
- [x] #95.  This is probably the priority
- [x] Back-fill data (i.e. extend the training dataset backwards in time).
- [x] Add more disks to OCF's ML server (currently has 8 x 12 TB disks in a ZFS RAIDZ array)

## Types of data
- [x] EUMETSAT SEVIRI RSS (2020 and 2021 is downloaded and converted to Zarr.)
- [x] Numerical Weather Predictions  (downloaded all data from 2016 to 2021.  Converted 2020 and 2021 to Zarr)
- [x] PV time series
- [x] GSP PV data from Sheffield Solar

**Comment by jacobbieker** [comment]
Just to note, my code works, but sometimes hangs and has to be restarted. I would think Airflow pipeline might be better suited for continually ingesting data?

**Comment by JackKelly** [comment]
Cool beans!

@AyrtonB what would you recommend for ingesting ~10 years of EUMETSAT data onto our "in-premises" Linux server?  I remember you were looking at a more recent alternative to Airflow (DAGster?)  Would you recommend we use custom code; or Airflow; or DAGster?  At the moment, we 'just' want data for ML experimentation.  Early in 2022 we'll also want an 'operational' data pipeline that gets data every 5 minutes :)

**Comment by peterdudfield** [comment]
PV data is current from '2010-12-15T13:10:00. to  '2019-08-20T23:00:00', Ill have a look at updating this

**Comment by JackKelly** [comment]
Awesome, thank you!

That data is from PVOutput.org.

I wrote a little Python library to download data from PVOutput.org: https://github.com/openclimatefix/pvoutput

PVOutput.org provide an API for _some_ of the data we need.  But the script also needs to scrape some data from the PVOutput.org HTML pages.

I haven't used the Python library for something like 2 years so I wouldn't be surprised if the PVOutput.org API and/or website are out of sync.

Also, OCF will need to pay PVOutput.org for a new subscription for a year's access to UK PV data (which costs something like $800 Australian dollars).  There is free API access but it's so slow as to be almost unusable for bulk-downloading lots of data.  I'll pay PVOutput.org this afternoon when I'm back in London and forward you the account details ;)

**Comment by JackKelly** [comment]
I've just had a quick read through the PVOutput code and the PVOutput.org API.

So, if I remember correctly, I think there are several steps:

1) Get a list of all the PV systems for the UK
2) Loop through each system and download a year of data at a time for that PV system.

**Comment by AyrtonB** [comment]
> @AyrtonB what would you recommend for ingesting ~10 years of EUMETSAT data onto our "in-premises" Linux server? I remember you were looking at a more recent alternative to Airflow ([Dagster](https://dagster.io/)?) Would you recommend we use custom code; or Airflow; or Dagster? At the moment, we 'just' want data for ML experimentation. Early in 2022 we'll also want an 'operational' data pipeline that gets data every 5 minutes :)

Apologies for the delay, missed the notification for this the first time round. Dagster or Airflow (doesn't matter too much which) will save a lot of hassle when you want the operational data pipeline (e.g. you don't want to be writing your own retry scripts) so it probably makes sense to build that from the start. If you want a super lightweight prototype for now then you could use something like `typer` to create a CLI for the code and then run it on a cron job.

Enjoy COP!

**Comment by JackKelly** [comment]
Thanks @AyrtonB !

@peterdudfield on the topic of downloading PV data... I've had a quick look through our PVOutput code I wrote 2 years ago and the PVOutput.org API and I've reminded myself that the API is quirky as hell.  TBH, top of my TODO list was to crack on with downloading the PVOutput.org data after I get back from COP, so I'm happy to do this task, if you want (but thanks loads for offering!)  Hopefully my previous experience of using the PVOutput.org API 2 years ago should mean I can do this task fairly quickly, and I quite like writing data download scripts :)

For a bit more context:

There's no simple way to get a list of all the PV systems in the UK.

The API has a search function.  And it looks like there's a new "country" parameter for the search function.  But the search only returns up to 30 PV systems, with no way to request subsequent "pages" of results.

So, IIRC, there are two options for finding all PV systems in the UK:

1) Use the [search API function](https://pvoutput.org/help/api_specification.html#search-service) across a geospatial grid (you can search for all PV systems within _x_km of a query point).  But you might miss PV systems if there are > 30.
2) Scrape the [map HTML web page](https://pvoutput.org/region.jsp?country=243).   But that seems to have changed since I wrote the Python code and now splits the UK up into a bunch of regions.

**Comment by peterdudfield** [comment]
Thanks @JackKelly , I'll have a play. Im conscious this is a high priority task, so if I can help out then it will be useful. 

Perhaps a status on the sat, and nwp data, would be good to add to the description above?

**Comment by JackKelly** [comment]
OK, cool, that'd be great if you could look into downloading the PVOutput.org data, thanks!

I think the PVOutput code can scrape the PVOutput.org map.  So I think the steps are:

1. Use [`pv_systems_for_country`](https://github.com/openclimatefix/pvoutput/blob/main/pvoutput/mapscraper.py#L14) to download the metadata for all PV systems for the UK.
2. Loop round each PV system and use [`get_batch_status`](https://github.com/openclimatefix/pvoutput/blob/main/pvoutput/pvoutput.py#L251) to download all timeseries data for that PV system.

You'll then need to save the PV data in the form that `nowcasting_dataset` expects (I'm not sure where the old code is to save the data to disk in the correct format, sorry!)

> Perhaps a status on the sat, and nwp data, would be good to add to the description above? 

will do.

I'll definitely do the NWP data as i've had lots of experience working with that data....

**Comment by peterdudfield** [comment]
Im getting 401 errors, but I think that is due to not having the 'premium' account. So i'll wait for you on that
https://pvoutput.org/help/api_specification.html#unauthorized-401-inaccessible-system-id

**Comment by peterdudfield** [comment]
This works thought
```
from pvoutput.mapscraper import get_pv_systems_for_country

pv_systems_for_uk = get_pv_systems_for_country(
    country='United Kingdom',  # See pvoutput.consts.PV_OUTPUT_COUNTRY_CODES for all recognised strings
    sort_by='capacity',
    ascending=False,
    max_pages=1  # For this demo, we'll just scrape the first page of the map
)
``
<img width="541" alt="Screenshot 2021-11-04 at 11 12 02" src="https://user-images.githubusercontent.com/34686298/140304045-8d938d13-46fb-402a-9483-2ef4e3230dda.png">
`

**Comment by jacobbieker** [comment]
The sat data should now be completely downloaded from 2020-01-01 to 2021-11-02, as well as for more of 2019 and 2018. The download script is paused while making the Zarr for 2020/2021 as otherwise the Zarr creation slows down by an order of magnitude. Once its created though, I'll restart it.

**Comment by peterdudfield** [comment]
Passive - data is here - https://github.com/openclimatefix/nowcasting_dataset/pull/342

**Comment by peterdudfield** [comment]
GSP data is from
2016- to 2021-10-01
GCS: filename = "gs://solar-pv-nowcasting-data/PV/GSP/v2/pv_gsp.zarr"
local: "/mnt/storage_b/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/PV/GSP/v2/pv_gsp.zarr"

**Comment by JackKelly** [comment]
Awesome, thank you!

**Comment by jacobbieker** [comment]
Satellite data is back to downloading, and is nearly done with 2019. Also, satellite cloud masks from 2018-10 to 2021 are downloaded now too.

**Comment by JackKelly** [comment]
Woo!  Very exciting!

**Comment by JackKelly** [comment]
Exciting stuff!  Great work!  The last piece of the puzzle is getting the NWP raw files converted to a Zarr intermediate... I'm working on that right now :slightly_smiling_face:

**Comment by peterdudfield** [comment]
> > Passive - data is here - #342. This can be used instead of PVoutput.org
> 
> Ive dropped Jamie a slack message about options to get more 5 mins data from Passiv. Currently only 2020 and 2021

Jamie hopes to get it to me by tomorrow (2021-11-10)

**Comment by peterdudfield** [comment]
I may need to re run the 'Sun' to work of the passive systems

**Comment by jacobbieker** [comment]
Satellite data is now on to 2017, so we should have 2018-2021 now downloaded

**Comment by JackKelly** [comment]
Good point!

I've changed the name of this issue to "Get data from 2020-01-01 to 2021-10-01".  I'll close this issue now.  I'll create a new issue for WP2 to back-fill all the way back to 2016 :slightly_smiling_face:
